apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: postgres-ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-postgres-demo:latest   # Ganti ke image registry kamu kalau di-push
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-0.postgres.postgres-ha.svc.cluster.local"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: postgres-ha
spec:
  selector:
    app: flask-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

